spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myplan?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update #validate #create update
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

flyway:
  enabled: true
  out-of-order: true
  encoding: UTF-8
  url: jdbc:mysql://localhost:3306
  schemas: user
  user: root
  password: pass